# Generated by Django 3.0.2 on 2021-02-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210213_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comments',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
